In [9]:
import pandas as pd
import numpy as np

memberData = pd.read_csv('Member.csv', dtype = {'IsInBlackList' : object})
#篩選出男性的資料
male = (memberData['GenderTypeDef'] == 'Male')
#篩選出註冊方式為Web的資料
web = (memberData['RegisterSourceTypeDef'] == 'Web')
#列出為男性且用Web註冊的資料
memberData[(male & web)]

,MemberId,Birthday,GenderTypeDef,RegisterSourceTypeDef,RegisterDateTime,MinOrderDate,OpenCardPresent,LastBirthdayPresentYear,IsInBlackList
9181,217820,1991-10-02,Male,Web,2016-05-20 00:56:59.587,2016-05-20,7282,0,NaN
9725,3297579,1980-07-08,Male,Web,2016-05-16 22:21:20.207,2016-05-18,1438,2017,NaN
9953,982794,2017-11-04,Male,Web,2017-10-25 20:17:47.170,2017-12-12,8052,0,NaN
9998,6106042,1983-05-28,Male,Web,2017-11-09 00:00:03.493,NaN,7693,2018,NaN
10903,2566385,1981-01-20,Male,Web,2016-01-03 21:12:15.740,2016-01-24,7693,2018,NaN
10913,5924304,1985-07-29,Male,Web,2017-09-26 21:25:43.357,2017-09-26,7693,0,NaN
11057,4137028,1995-10-07,Male,Web,2016-10-22 09:02:09.113,2016-10-30,7693,0,NaN
11142,5349111,1992-08-08,Male,Web,2017-05-22 20:47:38.510,2017-05-23,10342,0,NaN
11181,5385585,1987-03-26,Male,Web,2017-05-30 14:55:43.457,2017-05-30,10342,0,NaN
11813,80288,1986-03-12,Male,Web,2017-10-11 21:43:40.633,2017-10-11,7282,2018,NaN
13229,4022412,2002-02-23,Male,Web,2016-10-29 15:34:32.537,NaN,2577,2018,NaN
13594,5966557,1993-11-26,Male,Web,2017-10-07 21:16:05.143,2017-10-07,8052,0,NaN
14098,2402768,1990-02-04,Male,Web,2015-12-02 16:44:50.520,2015-12-02,630,2018,NaN
14609,4032317,1980-01-07,Male,Web,2016-09-28 19:49:58.527,2016-09-28,2294,2018,NaN
15037,1725098,1969-10-31,Male,Web,2017-04-29 23:33:30.760,2017-04-30,5489,2017,NaN
15569,3958749,1988-06-25,Male,Web,2016-09-15 02:30:53.400,2016-09-15,7693,0,NaN
15668,3101760,1985-10-01,Male,Web,2016-04-11 12:35:29.147,2016-04-11,1292,2017,NaN
16198,4809289,1987-07-13,Male,Web,2017-06-18 18:25:23.960,2017-06-18,5493,2017,NaN
16199,5355584,1995-03-23,Male,Web,2017-05-24 12:52:06.110,2017-05-24,5489,2018,NaN
18515,6015941,1998-10-31,Male,Web,2017-10-22 19:27:46.020,2017-10-22,7693,0,NaN
21530,1176532,1993-12-09,Male,Web,2016-06-28 23:19:44.303,NaN,1626,2017,NaN
21719,2008352,1978-12-03,Male,Web,2016-10-18 20:50:23.587,NaN,2577,2017,NaN
21720,2251396,1989-12-08,Male,Web,2015-11-11 22:20:30.803,NaN,544,2017,NaN
21721,3190754,1984-12-30,Male,Web,2016-04-28 15:04:21.977,NaN,1292,2017,NaN
22864,808498,1986-12-26,Male,Web,2015-09-14 17:55:57.163,2015-12-04,812,2017,NaN
28087,622391,1983-12-13,Male,Web,2017-01-20 12:12:53.163,2017-01-27,8052,0,NaN
29289,4684331,1985-02-09,Male,Web,2017-07-23 23:45:12.707,2017-07-23,5938,2018,NaN
30588,401400,1985-03-06,Male,Web,2017-07-25 09:20:35.353,2017-07-25,5938,2018,NaN
30844,3158185,1996-03-18,Male,Web,2016-09-13 15:02:37.893,2016-09-13,6547,2018,NaN
31222,1950359,1988-10-27,Male,Web,2017-07-10 23:03:56.043,2017-10-23,5938,2017,NaN
...,...,...,...,...,...,...,...,...,...
837857,3744860,1997-11-14,Male,Web,2016-08-02 15:08:13.147,2016-08-04,2051,2017,NaN
837858,4534755,1993-11-29,Male,Web,2016-12-19 02:06:33.830,2016-12-20,3581,2017,NaN
837859,1341340,1982-11-30,Male,Web,2016-08-02 21:52:35.580,2016-08-02,2051,2017,NaN
837860,3815551,1985-11-27,Male,Web,2016-08-15 23:41:58.427,2016-08-15,2051,2017,NaN
838257,5379375,1986-11-23,Male,Web,2017-05-29 11:50:58.673,2017-05-29,5493,2017,NaN
838333,1767507,1981-01-06,Male,Web,2017-11-12 00:45:29.277,NaN,7693,2018,NaN
838849,4424845,1992-11-20,Male,Web,2017-05-06 15:46:32.830,2017-05-06,5489,2017,NaN
838859,4128577,1982-11-20,Male,Web,2017-03-12 19:13:55.340,2017-03-12,6547,2017,NaN
839147,761352,1993-11-03,Male,Web,2017-10-12 19:32:30.800,NaN,7282,2017,NaN
839788,6250934,1996-01-11,Male,Web,2017-12-07 20:21:07.727,2017-12-07,8052,2018,NaN
840158,3643226,2000-10-30,Male,Web,2016-07-15 17:33:52.703,2016-07-15,7282,0,NaN
840532,2281522,1980-01-01,Male,Web,2015-12-01 20:08:50.967,2015-12-01,630,2018,NaN
840859,6181194,1992-03-29,Male,Web,2017-11-28 15:29:36.133,2017-12-08,10342,0,NaN
840898,6249112,1971-01-31,Male,Web,2017-12-07 13:11:57.617,2017-12-08,8052,2018,NaN
841336,5317706,1987-01-16,Male,Web,2017-05-16 10:52:32.867,2017-05-21,5489,2018,NaN
842052,2020822,2009-01-25,Male,Web,2017-11-10 00:53:11.543,NaN,7693,2018,NaN
842251,1697740,1990-05-05,Male,Web,2016-07-02 23:45:28.813,2016-07-02,7693,2018,NaN
847243,1458916,1996-04-21,Male,Web,2016-02-28 18:49:39.930,2016-02-28,5489,2018,NaN
847244,1769259,1992-04-25,Male,Web,2015-09-22 00:15:00.897,2015-09-27,0,2018,NaN
847245,2228673,1982-01-20,Male,Web,2016-10-06 13:24:17.657,2016-10-06,3581,2018,NaN
847246,1882999,1989-01-28,Male,Web,2015-10-10 09:45:33.340,2015-10-10,467,2018,NaN
847247,2454247,1987-04-08,Male,Web,2015-12-10 14:25:35.503,2015-12-18,630,2018,NaN
847248,2340014,1997-01-26,Male,Web,2017-06-10 23:23:27.237,2017-06-10,5493,2018,NaN
847249,2872604,1989-07-09,Male,Web,2016-02-29 20:37:52.557,2016-02-29,2051,2017,NaN
847250,3138884,1986-01-01,Male,Web,2016-04-18 18:26:29.413,2016-04-18,1292,2018,NaN
847251,3145589,1991-06-30,Male,Web,2016-04-20 00:38:43.810,2016-04-20,1292,2017,NaN
847252,3410954,2001-04-11,Male,Web,2016-06-05 13:08:58.773,2016-07-15,1626,2018,NaN
847253,3587636,1980-01-27,Male,Web,2016-07-06 18:45:29.290,2016-07-19,1838,2018,NaN
847254,3970427,1981-01-08,Male,Web,2016-09-17 07:47:56.443,2016-09-17,2577,2018,NaN
852528,4428815,1995-05-01,Male,Web,2016-11-29 21:14:27.457,2016-11-29,2664,2018,NaN